name: import-solution

# Import solution to Test environment 

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Name of the solution in dataverse"
        required: true
        default: TestSolution
      solution_version:
        description: "Version of the solution to import to test environment"
        required: true
        default: v1.0.0.0      
      solution-upgrade:
        description: "Do solution upgrade?"
        required: true
        default: false
      use_deployment_settings_file:
          description: "use_deployment_settings_file"
          required: true
          default: false

env:

#edit your values here

  ENVIRONMENT_URL: 'https://org80cb9b9d.crm8.dynamics.com/'

  CLIENT_ID: '277fac91-2641-4aee-952a-0e0dc026b695'

  TENANT_ID: 'fdd67221-13a8-4fc7-9764-c6f6ac35600f'

  REPO_NAME: Solution365
  
permissions: 
 id-token: write
 contents: write
 

jobs:

  export-unpack-commit:

    runs-on: ubuntu-latest
     
    steps:

    #checkout branch
     - name: create or checkout branch
       uses: actions/checkout@v4
       with:
        ref: dev
     - name: List files in the directory
       run:
         ls ${{ github.workspace }}

    #setup environment
     - name: setup .Net SDK
       uses: actions/setup-dotnet@3.0.2
       with:
        dotnet-version: '8.0.x'
        
     # - name: Add nuget source
     #  run: dotnet nuget add source ${{ env.NUGET_SOURCE_PATH }}

     
    #install power platform
     - name: install power platform tools
       uses: microsoft/powerplatform-actions/actions-install@v1.7.0
        
     - name: who am I?
       uses: microsoft/powerplatform-actions/who-am-i@v1.7.0
       with:
        app-id:  ${{ env.CLIENT_ID  }}
        client-secret: ${{secrets.PowerPlatformSPN}}       
        tenant-id:  ${{ env.TENANT_ID  }}
        environment-url:  ${{ env.ENVIRONMENT_URL  }}

     - name: import-solution action
       uses: microsoft/powerplatform-actions/import-solution@v1.7.0
       with:
        app-id:  ${{ env.CLIENT_ID  }}
        client-secret: ${{secrets.PowerPlatformSPN}}       
        tenant-id:  ${{ env.TENANT_ID  }}
        environment-url:  ${{ env.ENVIRONMENT_URL  }}
        solution-name: ${{ github.event.inputs.solution_name  }}
        solution-file: ${{ github.event.repository.name }}/${{github.event.inputs.solution_name }}_${{github.event.inputs.solution_version }}_managed.zip
        force-overwrite: false
        publish-changes: false
        stage-and-upgrade: ${{github.event.inputs.solution-upgrade}}
        use-deployment-settings-file: ${{github.event.inputs.use_deployment_settings_file}}

    
      
         
         

        

        













       
    
